version: "3"
services:
  backend:
    build:
      context: .
    restart: always
    ports:
      - 8080:80
    depends_on:
      - database

  database:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sleeping_news
    volumes:
      - db-sleeping-news:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db-sleeping-news: